# Generated by Django 5.0.4 on 2024-04-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('higher_degree', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('years_of_experience', models.IntegerField()),
                ('current_ctc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_ctc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('np', models.IntegerField()),
                ('counter', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('review_job_description', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
